'use strict';
//let arr = ['plum','gerald','repac'];
//console.log(arr[0]);
//console.log("arr"+"- object");
//console.log(5 + +"- object");
//let answer = + prompt("Есть ли Вам 18","Да");
//console.log(typeof(answer));
let incr = 10,decr = 10;
//incr ++;
//decr --;
console.log(incr++);
console.log(decr--);
console.log(5%2);
console.log("2"== 2);
console.log("2"=== 2);
let isCheked = false,isClose = true;
console.log(isCheked || !isClose);
console.log(!isCheked && !isClose);
console.log(isCheked || !isClose);
//a = 5;
//console.log(a);